import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS_HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...CORS_HEADERS}})}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS_HEADERS});if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Missing Authorization header'},401);
 if(Number(req.headers.get('content-length')??0)>65536)return json({error:'Request too large'},413);
 let body:Record<string,unknown>;try{body=await req.json()}catch{return json({error:'Invalid JSON body'},400)}
 const agent_id=body.agent_id as string|undefined,tool_name=body.tool_name as string|undefined,task_id=(body.task_id as string|undefined)??null,risk_level=body.risk_level as string|undefined,idempotency_key=body.idempotency_key as string|undefined;const args=(body.arguments as Record<string,unknown>)??{};if(!agent_id||!tool_name||!risk_level||!idempotency_key)return json({error:'agent_id, tool_name, risk_level, and idempotency_key are required'},400);if(!['low','medium','high'].includes(risk_level))return json({error:'invalid risk level'},422);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:u,error:ue}=await user.auth.getUser();if(ue||!u?.user)return json({error:'Invalid or expired session'},401);const admin=createClient(url,secret);
 const {data:agent,error:ae}=await admin.from('aios_agents').select('id,organization_id,status').eq('id',agent_id).maybeSingle();if(ae)return json({error:'Agent lookup failed'},500);if(!agent)return json({error:'Agent not found'},404);if(agent.status==='suspended')return json({error:'Agent is suspended'},403);const {data:member,error:me}=await user.rpc('aios_is_org_member',{org_id:agent.organization_id});if(me)return json({error:'Authorization check failed'},500);if(!member)return json({error:'Not authorized for this organization'},403);
 const {data:existing,error:ee}=await admin.from('aios_tool_invocations').select('id,status,approval_id,arguments_hash,tool_key').eq('organization_id',agent.organization_id).eq('idempotency_key',idempotency_key).maybeSingle();if(ee)return json({error:'Invocation lookup failed'},500);if(existing){if(existing.arguments_hash && existing.tool_key!==tool_name)return json({error:'Idempotency key is already bound to a different invocation'},409);return json({invocation_id:existing.id,status:existing.status,approval_id:existing.approval_id,idempotent_replay:true},200)}
 const {data:inv,error:ie}=await admin.from('aios_tool_invocations').insert({organization_id:agent.organization_id,agent_id:agent.id,task_id,tool_name,tool_key:tool_name,arguments:args,risk_level,requested_by:u.user.id,idempotency_key,request_id:crypto.randomUUID()}).select('id,status,approval_id,tool_key,authorization_version').single();if(ie){if(ie.code==='23505')return json({error:'Duplicate invocation prevented by idempotency policy'},409);if(ie.code==='42501')return json({error:'Invocation not authorized'},403);if(ie.code==='22023')return json({error:'Invocation failed registry validation'},422);if(ie.code==='23514')return json({error:'Invocation failed integrity validation'},422);return json({error:'Failed to create invocation'},500)}
 return json({invocation_id:inv.id,status:inv.status,gated:inv.status==='requires_approval',agent_id:agent.id,tool_key:inv.tool_key,approval_id:inv.approval_id},201);
});
