begin;
create schema if not exists private;
revoke all on schema private from public,anon,authenticated;
grant usage on schema private to authenticated;
create table if not exists public.aios_tools(id uuid primary key default gen_random_uuid(),tool_key text not null unique,name text not null,description text not null,version integer not null default 1,category text not null default 'general',risk_level text not null default 'low' check(risk_level in('low','medium','high')),input_schema jsonb not null default '{}'::jsonb,output_schema jsonb not null default '{}'::jsonb,handler text not null,status text not null default 'active' check(status in('active','disabled','deprecated')),is_enabled boolean not null default true,requires_approval boolean not null default false,timeout_ms integer not null default 15000 check(timeout_ms between 100 and 120000),rate_limit integer,idempotency_required boolean not null default true,external_service text,credential_reference text,capabilities jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.aios_evaluations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.aios_organizations(id) on delete cascade,agent_id uuid references public.aios_agents(id),mission_id uuid references public.aios_missions(id),task_id uuid not null references public.aios_tasks(id),invocation_id uuid references public.aios_tool_invocations(id),overall_score numeric(5,4) not null check(overall_score between 0 and 1),correctness numeric(5,4) not null check(correctness between 0 and 1),completeness numeric(5,4) not null check(completeness between 0 and 1),policy_compliance numeric(5,4) not null check(policy_compliance between 0 and 1),tool_efficiency numeric(5,4) not null check(tool_efficiency between 0 and 1),execution_success numeric(5,4) not null check(execution_success between 0 and 1),summary text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

alter table public.aios_tool_invocations add column if not exists idempotency_key text;
alter table public.aios_tool_invocations add column if not exists tool_key text;
alter table public.aios_tool_invocations add column if not exists authorization_version integer;
alter table public.aios_tool_invocations add column if not exists arguments_hash text;
alter table public.aios_tool_invocations add column if not exists result_hash text;
alter table public.aios_tool_invocations add column if not exists evaluated_at timestamptz;
alter table public.aios_tool_invocations add column if not exists started_at timestamptz;
alter table public.aios_tool_invocations add column if not exists error_code text;
alter table public.aios_tool_invocations add column if not exists error_message text;
alter table public.aios_tool_invocations add column if not exists retry_count integer not null default 0;
alter table public.aios_tool_invocations add column if not exists request_id uuid;
alter table public.aios_approvals add column if not exists invocation_id uuid references public.aios_tool_invocations(id);
alter table public.aios_approvals add column if not exists tool_key text;
alter table public.aios_approvals add column if not exists arguments_hash text;
alter table public.aios_approvals add column if not exists approval_version integer;
alter table public.aios_approvals add column if not exists approval_reason text;
alter table public.aios_approvals add column if not exists expires_at timestamptz;
alter table public.aios_approvals add column if not exists approved_by uuid references auth.users(id);
alter table public.aios_approvals add column if not exists approved_at timestamptz;
alter table public.aios_audit_events add column if not exists actor_user_id uuid references auth.users(id);
alter table public.aios_audit_events add column if not exists actor_type text not null default 'system';
alter table public.aios_audit_events add column if not exists mission_id uuid references public.aios_missions(id);
alter table public.aios_audit_events add column if not exists invocation_id uuid references public.aios_tool_invocations(id);
alter table public.aios_audit_events add column if not exists tool_name text;
alter table public.aios_audit_events add column if not exists arguments_hash text;
alter table public.aios_audit_events add column if not exists result_hash text;
alter table public.aios_audit_events add column if not exists approval_id uuid references public.aios_approvals(id);
alter table public.aios_audit_events add column if not exists previous_state text;
alter table public.aios_audit_events add column if not exists new_state text;
alter table public.aios_audit_events add column if not exists previous_event_hash text;
alter table public.aios_audit_events add column if not exists event_hash text;
alter table public.aios_audit_events add column if not exists request_id uuid;
alter table public.aios_model_runs add column if not exists input_hash text;
alter table public.aios_model_runs add column if not exists output_hash text;
alter table public.aios_model_runs add column if not exists prompt_reference text;
alter table public.aios_model_runs add column if not exists status text not null default 'succeeded';
alter table public.aios_model_runs add column if not exists error_code text;
alter table public.aios_demo_support_tickets add column if not exists organization_id uuid references public.aios_organizations(id) on delete cascade;
update public.aios_tool_invocations set tool_key=tool_name where tool_key is null;
create unique index if not exists uq_aios_invocation_idempotency on public.aios_tool_invocations(organization_id,idempotency_key) where idempotency_key is not null;
create index if not exists idx_aios_invocations_task_created on public.aios_tool_invocations(task_id,created_at desc);
create index if not exists idx_aios_invocations_status on public.aios_tool_invocations(organization_id,status);
create unique index if not exists uq_aios_approvals_invocation on public.aios_approvals(invocation_id) where invocation_id is not null;
create index if not exists idx_aios_approvals_expires on public.aios_approvals(organization_id,status,expires_at);
create index if not exists idx_aios_evaluations_agent_created on public.aios_evaluations(agent_id,created_at desc);
create index if not exists idx_aios_evaluations_org_created on public.aios_evaluations(organization_id,created_at desc);
create index if not exists idx_aios_audit_invocation on public.aios_audit_events(invocation_id,created_at);
create index if not exists idx_aios_demo_tickets_org_created on public.aios_demo_support_tickets(organization_id,created_at desc);

-- Replace broad ALL policies with operation-specific policies.
drop policy if exists aios_departments_member on public.aios_departments; drop policy if exists aios_projects_member on public.aios_projects; drop policy if exists aios_missions_member on public.aios_missions; drop policy if exists aios_tasks_member on public.aios_tasks; drop policy if exists aios_memory_member on public.aios_memory; drop policy if exists aios_model_runs_member on public.aios_model_runs; drop policy if exists aios_approvals_delete on public.aios_approvals;
create policy aios_departments_select on public.aios_departments for select to authenticated using((select public.aios_is_org_member(organization_id)));
create policy aios_departments_insert on public.aios_departments for insert to authenticated with check((select public.aios_is_org_admin(organization_id)));
create policy aios_departments_update on public.aios_departments for update to authenticated using((select public.aios_is_org_admin(organization_id))) with check((select public.aios_is_org_admin(organization_id)));
create policy aios_departments_delete on public.aios_departments for delete to authenticated using((select public.aios_is_org_admin(organization_id)));
create policy aios_projects_select on public.aios_projects for select to authenticated using((select public.aios_is_org_member(organization_id)));
create policy aios_projects_insert on public.aios_projects for insert to authenticated with check((select public.aios_is_org_member(organization_id)));
create policy aios_projects_update on public.aios_projects for update to authenticated using((select public.aios_is_org_member(organization_id))) with check((select public.aios_is_org_member(organization_id)));
create policy aios_projects_delete on public.aios_projects for delete to authenticated using((select public.aios_is_org_admin(organization_id)));
create policy aios_missions_select on public.aios_missions for select to authenticated using((select public.aios_is_org_member(organization_id)));
create policy aios_missions_insert on public.aios_missions for insert to authenticated with check((select public.aios_is_org_member(organization_id)));
create policy aios_missions_update on public.aios_missions for update to authenticated using((select public.aios_is_org_member(organization_id))) with check((select public.aios_is_org_member(organization_id)));
create policy aios_missions_delete on public.aios_missions for delete to authenticated using((select public.aios_is_org_admin(organization_id)));
create policy aios_tasks_select on public.aios_tasks for select to authenticated using((select public.aios_is_org_member(organization_id)));
create policy aios_tasks_insert on public.aios_tasks for insert to authenticated with check((select public.aios_is_org_member(organization_id)));
create policy aios_tasks_update on public.aios_tasks for update to authenticated using((select public.aios_is_org_member(organization_id))) with check((select public.aios_is_org_member(organization_id)));
create policy aios_tasks_delete on public.aios_tasks for delete to authenticated using((select public.aios_is_org_admin(organization_id)));
create policy aios_memory_select on public.aios_memory for select to authenticated using((select public.aios_is_org_member(organization_id)));
create policy aios_memory_insert on public.aios_memory for insert to authenticated with check((select public.aios_is_org_member(organization_id)));
create policy aios_memory_update on public.aios_memory for update to authenticated using((select public.aios_is_org_admin(organization_id))) with check((select public.aios_is_org_admin(organization_id)));
create policy aios_memory_delete on public.aios_memory for delete to authenticated using((select public.aios_is_org_admin(organization_id)));
create policy aios_model_runs_select on public.aios_model_runs for select to authenticated using((select public.aios_is_org_member(organization_id)));
create policy aios_model_runs_insert on public.aios_model_runs for insert to authenticated with check((select public.aios_is_org_member(organization_id)));
create policy aios_model_runs_update on public.aios_model_runs for update to authenticated using((select public.aios_is_org_admin(organization_id))) with check((select public.aios_is_org_admin(organization_id)));
create policy aios_model_runs_delete on public.aios_model_runs for delete to authenticated using((select public.aios_is_org_admin(organization_id)));
drop policy if exists aios_approvals_select on public.aios_approvals;
create policy aios_approvals_select_v2 on public.aios_approvals for select to authenticated using((select public.aios_is_org_member(organization_id)));
drop policy if exists aios_tool_invocations_select on public.aios_tool_invocations;
create policy aios_tool_invocations_select_v2 on public.aios_tool_invocations for select to authenticated using((select public.aios_is_org_member(organization_id)));

alter table public.aios_tools enable row level security; alter table public.aios_evaluations enable row level security;
create policy aios_tools_select on public.aios_tools for select to authenticated using(is_enabled=true and status='active');
create policy aios_evaluations_select on public.aios_evaluations for select to authenticated using((select public.aios_is_org_member(organization_id)));
revoke insert,update,delete on public.aios_audit_events from anon,authenticated;
revoke insert,update,delete on public.aios_tools from anon,authenticated;
revoke insert,update,delete on public.aios_evaluations from anon,authenticated;

drop policy if exists aios_demo_tickets_read on public.aios_demo_support_tickets;
create policy aios_demo_tickets_read on public.aios_demo_support_tickets for select to authenticated using(organization_id is not null and (select public.aios_is_org_member(organization_id)));
commit;
