begin;
create or replace function private.aios_is_org_member(org_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.aios_organization_members m where m.organization_id=$1 and m.user_id=(select auth.uid())); $$;
create or replace function private.aios_is_org_admin(org_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.aios_organization_members m where m.organization_id=$1 and m.user_id=(select auth.uid()) and m.role in('owner','admin')); $$;
create or replace function private.aios_current_org_role(org_id uuid) returns text language sql stable security definer set search_path='' as $$ select m.role from public.aios_organization_members m where m.organization_id=$1 and m.user_id=(select auth.uid()) limit 1; $$;
create or replace function public.aios_is_org_member(org_id uuid) returns boolean language sql stable security invoker set search_path='' as $$ select private.aios_is_org_member($1); $$;
create or replace function public.aios_is_org_admin(org_id uuid) returns boolean language sql stable security invoker set search_path='' as $$ select private.aios_is_org_admin($1); $$;
create or replace function public.aios_current_org_role(org_id uuid) returns text language sql stable security invoker set search_path='' as $$ select private.aios_current_org_role($1); $$;
create or replace function public.aios_can_approve(org_id uuid) returns boolean language sql stable security invoker set search_path='' as $$ select private.aios_is_org_admin($1); $$;
create or replace function public.aios_can_manage_agent(org_id uuid) returns boolean language sql stable security invoker set search_path='' as $$ select private.aios_is_org_admin($1); $$;
create or replace function public.aios_can_manage_contract(org_id uuid) returns boolean language sql stable security invoker set search_path='' as $$ select private.aios_is_org_admin($1); $$;

create or replace function private.aios_task_status_guard() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status then if not((old.status='queued' and new.status in('assigned','ready','running','cancelled','expired')) or(old.status='assigned' and new.status in('ready','running','cancelled','expired')) or(old.status='ready' and new.status in('running','cancelled','expired')) or(old.status='running' and new.status in('blocked_pending_approval','completed','failed','cancelled','expired')) or(old.status='blocked_pending_approval' and new.status in('approved','failed','cancelled','expired')) or(old.status='approved' and new.status in('running','cancelled','expired'))) then raise exception 'invalid task state transition: % -> %',old.status,new.status; end if; end if; if new.status='running' and new.started_at is null then new.started_at=now(); end if; if new.status in('completed','failed','cancelled','expired') and new.completed_at is null then new.completed_at=now(); end if; return new; end; $$;
create or replace function private.aios_invocation_status_guard() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status then if not((old.status='requested' and new.status in('evaluating','requires_approval','approved','denied','failed','cancelled','expired')) or(old.status='evaluating' and new.status in('requires_approval','approved','denied','failed','cancelled','expired')) or(old.status='requires_approval' and new.status in('approved','denied','cancelled','expired')) or(old.status='approved' and new.status in('executing','cancelled','expired')) or(old.status='executing' and new.status in('succeeded','failed','cancelled','expired'))) then raise exception 'invalid invocation state transition: % -> %',old.status,new.status; end if; end if; return new; end; $$;
create or replace function private.aios_approval_status_guard() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status and not(old.status='pending' and new.status in('approved','rejected','expired')) then raise exception 'invalid approval state transition: % -> %',old.status,new.status; end if; return new; end; $$;
create or replace function private.aios_mission_status_guard() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status then if not((old.status='queued' and new.status in('running','cancelled','expired')) or(old.status='running' and new.status in('blocked_pending_approval','completed','failed','cancelled','expired')) or(old.status='blocked_pending_approval' and new.status in('running','completed','failed','cancelled','expired'))) then raise exception 'invalid mission state transition: % -> %',old.status,new.status; end if; end if; if new.status='running' and new.started_at is null then new.started_at=now(); end if; if new.status in('completed','failed','cancelled','expired') and new.completed_at is null then new.completed_at=now(); end if; return new; end; $$;
drop trigger if exists trg_aios_task_status_guard on public.aios_tasks; create trigger trg_aios_task_status_guard before update of status on public.aios_tasks for each row execute function private.aios_task_status_guard();
drop trigger if exists trg_aios_invocation_status_guard on public.aios_tool_invocations; create trigger trg_aios_invocation_status_guard before update of status on public.aios_tool_invocations for each row execute function private.aios_invocation_status_guard();
drop trigger if exists trg_aios_approval_status_guard on public.aios_approvals; create trigger trg_aios_approval_status_guard before update of status on public.aios_approvals for each row execute function private.aios_approval_status_guard();
drop trigger if exists trg_aios_mission_status_guard on public.aios_missions; create trigger trg_aios_mission_status_guard before update of status on public.aios_missions for each row execute function private.aios_mission_status_guard();

create or replace function private.aios_enforce_agent_authority() returns trigger language plpgsql security definer set search_path='' as $$ declare v_agent record; v_contract record; v_tool record; v_reason text; v_approval uuid; begin select a.id,a.organization_id,a.status into v_agent from public.aios_agents a where a.id=new.agent_id; if v_agent.id is null then raise exception 'agent not found'; end if; if v_agent.organization_id is distinct from new.organization_id then raise exception 'agent organization mismatch'; end if; if v_agent.status='suspended' then new.status='denied'; new.result=jsonb_build_object('kernel_reason','agent suspended'); return new; end if; select c.id,c.version,c.risk_level,c.allowed_tools into v_contract from public.aios_contracts c where c.agent_id=new.agent_id and c.organization_id=new.organization_id and c.is_active order by c.version desc limit 1; if v_contract.id is null then new.status='denied'; new.result=jsonb_build_object('kernel_reason','no active contract'); return new; end if; select t.id,t.tool_key,t.risk_level,t.is_enabled,t.status,t.requires_approval into v_tool from public.aios_tools t where t.tool_key=coalesce(new.tool_key,new.tool_name); if v_tool.id is null then new.status='denied'; new.result=jsonb_build_object('kernel_reason','unknown tool'); return new; end if; if not v_tool.is_enabled or v_tool.status<>'active' then new.status='denied'; new.result=jsonb_build_object('kernel_reason','tool disabled'); return new; end if; new.tool_key=v_tool.tool_key; new.tool_name=v_tool.tool_key; new.arguments=coalesce(new.arguments,'{}'::jsonb); new.arguments_hash=encode(digest(new.arguments::text,'sha256'),'hex'); if not(v_contract.allowed_tools ? v_tool.tool_key) then v_reason='tool not in active contract'; elsif public.aios_risk_rank(v_tool.risk_level)>public.aios_risk_rank(v_contract.risk_level) or public.aios_risk_rank(new.risk_level)>public.aios_risk_rank(v_contract.risk_level) then v_reason='risk exceeds contract ceiling'; elsif v_tool.requires_approval then v_reason='tool requires approval'; end if; if v_reason is not null then new.status='requires_approval'; new.result=coalesce(new.result,'{}'::jsonb)||jsonb_build_object('kernel_reason',v_reason,'contract_version',v_contract.version); insert into public.aios_approvals(organization_id,agent_id,task_id,invocation_id,action,risk_level,resource,reason,approval_reason,tool_key,arguments_hash,approval_version,status,expires_at) values(new.organization_id,new.agent_id,new.task_id,new.id,new.tool_key,new.risk_level,new.tool_key,v_reason,v_reason,v_tool.tool_key,new.arguments_hash,v_contract.version,'pending',now()+interval '30 minutes') returning id into v_approval; new.approval_id=v_approval; else new.authorization_version=v_contract.version; new.status='approved'; end if; return new; end; $$;
drop trigger if exists trg_aios_enforce_agent_authority on public.aios_tool_invocations; create trigger trg_aios_enforce_agent_authority before insert on public.aios_tool_invocations for each row execute function private.aios_enforce_agent_authority();

create or replace function private.aios_audit_append() returns trigger language plpgsql security definer set search_path='' as $$ declare v_prev text; begin perform pg_advisory_xact_lock(hashtextextended(coalesce(new.organization_id::text,''),0)); select event_hash into v_prev from public.aios_audit_events where organization_id=new.organization_id order by created_at desc,id desc limit 1; new.previous_event_hash=coalesce(v_prev,'GENESIS:'||new.organization_id::text); new.event_hash=encode(digest(jsonb_build_object('id',new.id,'organization_id',new.organization_id,'actor_user_id',new.actor_user_id,'actor_type',new.actor_type,'agent_id',new.agent_id,'mission_id',new.mission_id,'task_id',new.task_id,'invocation_id',new.invocation_id,'event_type',new.event_type,'previous_state',new.previous_state,'new_state',new.new_state,'tool_name',new.tool_name,'risk_level',new.risk_level,'arguments_hash',new.arguments_hash,'result_hash',new.result_hash,'approval_id',new.approval_id,'created_at',new.created_at,'metadata',new.metadata,'previous_event_hash',new.previous_event_hash)::text||new.previous_event_hash,'sha256'),'hex'); return new; end; $$;
create or replace function private.aios_audit_immutable() returns trigger language plpgsql security definer set search_path='' as $$ begin raise exception 'audit ledger is append-only' using errcode='42501'; end; $$;

create or replace function private.aios_log_task_status() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status is distinct from old.status then insert into public.aios_audit_events(organization_id,actor_user_id,actor_type,agent_id,mission_id,task_id,event_type,risk_level,action,decision,previous_state,new_state,metadata) values(new.organization_id,(select auth.uid()),case when(select auth.uid()) is null then 'system' else 'user' end,new.assigned_agent_id,new.mission_id,new.id,'task_status_changed',new.risk_level,new.title,new.status,old.status,new.status,jsonb_build_object('task_id',new.id)); end if; return new; end; $$;
create or replace function private.aios_log_mission_status() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status is distinct from old.status then insert into public.aios_audit_events(organization_id,actor_user_id,actor_type,mission_id,event_type,risk_level,action,decision,previous_state,new_state,metadata) values(new.organization_id,(select auth.uid()),case when(select auth.uid()) is null then 'system' else 'user' end,new.id,'mission_status_changed','low',new.title,new.status,old.status,new.status,jsonb_build_object('mission_id',new.id)); end if; return new; end; $$;
create or replace function private.aios_log_invocation() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='INSERT' then insert into public.aios_audit_events(organization_id,actor_user_id,actor_type,agent_id,mission_id,task_id,invocation_id,event_type,risk_level,action,decision,new_state,tool_name,arguments_hash,approval_id,request_id,metadata) values(new.organization_id,new.requested_by,case when new.requested_by is null then 'agent' else 'user' end,new.agent_id,(select mission_id from public.aios_tasks where id=new.task_id),new.task_id,new.id,'tool_invocation_requested',new.risk_level,new.tool_key,new.status,new.status,new.tool_key,new.arguments_hash,new.approval_id,new.request_id,jsonb_build_object('contract_version',new.authorization_version)); elsif new.status is distinct from old.status then insert into public.aios_audit_events(organization_id,actor_user_id,actor_type,agent_id,mission_id,task_id,invocation_id,event_type,risk_level,action,decision,previous_state,new_state,tool_name,arguments_hash,result_hash,approval_id,request_id,metadata) values(new.organization_id,(select auth.uid()),case when(select auth.uid()) is null then 'system' else 'user' end,new.agent_id,(select mission_id from public.aios_tasks where id=new.task_id),new.task_id,new.id,'tool_invocation_status_changed',new.risk_level,new.tool_key,new.status,old.status,new.status,new.tool_key,new.arguments_hash,new.result_hash,new.approval_id,new.request_id,jsonb_build_object('error_code',new.error_code)); end if; return new; end; $$;
create or replace function private.aios_log_approval() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='INSERT' or new.status is distinct from old.status then insert into public.aios_audit_events(organization_id,actor_user_id,actor_type,agent_id,mission_id,task_id,invocation_id,event_type,risk_level,action,decision,previous_state,new_state,tool_name,arguments_hash,approval_id,metadata) values(new.organization_id,coalesce(new.reviewed_by,new.approved_by),case when coalesce(new.reviewed_by,new.approved_by) is null then 'system' else 'user' end,new.agent_id,(select mission_id from public.aios_tasks where id=new.task_id),new.task_id,new.invocation_id,'approval_changed',new.risk_level,new.tool_key,new.status,case when tg_op='UPDATE' then old.status else null end,new.status,new.tool_key,new.arguments_hash,new.id,jsonb_build_object('reason',coalesce(new.approval_reason,new.reason),'approval_version',new.approval_version)); end if; return new; end; $$;

drop trigger if exists trg_aios_log_task_status_audit on public.aios_tasks; create trigger trg_aios_log_task_status_audit after update of status on public.aios_tasks for each row execute function private.aios_log_task_status();
drop trigger if exists trg_aios_log_mission_status_audit on public.aios_missions; create trigger trg_aios_log_mission_status_audit after update of status on public.aios_missions for each row execute function private.aios_log_mission_status();
drop trigger if exists trg_aios_log_tool_invocation_audit on public.aios_tool_invocations; create trigger trg_aios_log_tool_invocation_audit after insert or update of status on public.aios_tool_invocations for each row execute function private.aios_log_invocation();
drop trigger if exists trg_aios_log_approval_audit on public.aios_approvals; create trigger trg_aios_log_approval_audit after insert or update of status on public.aios_approvals for each row execute function private.aios_log_approval();

create or replace function private.verify_audit_chain(p_organization_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare r record; v_prev text:='GENESIS:'||p_organization_id::text; v_expected text; v_count int:=0; v_first uuid; v_last uuid; begin if not private.aios_is_org_member(p_organization_id) then raise exception 'not authorized' using errcode='42501'; end if; for r in select * from public.aios_audit_events where organization_id=p_organization_id order by created_at,id loop v_count=v_count+1; if v_first is null then v_first=r.id; end if; v_last=r.id; v_expected=encode(digest(jsonb_build_object('id',r.id,'organization_id',r.organization_id,'actor_user_id',r.actor_user_id,'actor_type',r.actor_type,'agent_id',r.agent_id,'mission_id',r.mission_id,'task_id',r.task_id,'invocation_id',r.invocation_id,'event_type',r.event_type,'previous_state',r.previous_state,'new_state',r.new_state,'tool_name',r.tool_name,'risk_level',r.risk_level,'arguments_hash',r.arguments_hash,'result_hash',r.result_hash,'approval_id',r.approval_id,'created_at',r.created_at,'metadata',r.metadata,'previous_event_hash',v_prev)::text||v_prev,'sha256'),'hex'); if r.previous_event_hash is distinct from v_prev or r.event_hash is distinct from v_expected then return jsonb_build_object('valid',false,'events_checked',v_count,'first_event',v_first,'last_event',r.id,'broken_event_id',r.id,'expected_hash',v_expected,'actual_hash',r.event_hash); end if; v_prev=r.event_hash; end loop; return jsonb_build_object('valid',true,'events_checked',v_count,'first_event',v_first,'last_event',v_last,'broken_event_id',null,'expected_hash',null,'actual_hash',null); end; $$;
create or replace function public.verify_audit_chain(p_organization_id uuid) returns jsonb language sql stable security invoker set search_path='' as $$ select private.verify_audit_chain($1); $$;

create or replace function private.aios_record_evaluation(p_task_id uuid,p_invocation_id uuid,p_correctness numeric,p_completeness numeric,p_policy numeric,p_efficiency numeric,p_execution numeric,p_summary text default null) returns public.aios_evaluations language plpgsql security definer set search_path='' as $$ declare v public.aios_tasks; e public.aios_evaluations; s numeric; t numeric; begin select * into v from public.aios_tasks where id=p_task_id; if v.id is null then raise exception 'task not found'; end if; if not private.aios_is_org_member(v.organization_id) then raise exception 'not authorized' using errcode='42501'; end if; s=round((p_correctness+p_completeness+p_policy+p_efficiency+p_execution)/5,4); insert into public.aios_evaluations(organization_id,agent_id,mission_id,task_id,invocation_id,overall_score,correctness,completeness,policy_compliance,tool_efficiency,execution_success,summary) values(v.organization_id,v.assigned_agent_id,v.mission_id,v.id,p_invocation_id,s,p_correctness,p_completeness,p_policy,p_efficiency,p_execution,p_summary) returning * into e; select greatest(0,least(100,coalesce(a.trust_score,0)*0.7+s*100*0.3)) into t from public.aios_agents a where a.id=v.assigned_agent_id; update public.aios_agents set trust_score=round(t,2) where id=v.assigned_agent_id; return e; end; $$;
create or replace function private.aios_agent_trust_explain(p_agent_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare o uuid; s numeric; c int; f int; d int; r int; a numeric; begin select organization_id,trust_score into o,s from public.aios_agents where id=p_agent_id; if o is null then return jsonb_build_object('error','agent not found'); end if; if not private.aios_is_org_member(o) then return jsonb_build_object('error','not authorized'); end if; select count(*) filter(where status='completed'),count(*) filter(where status='failed') into c,f from public.aios_tasks where assigned_agent_id=p_agent_id; select count(*) into d from public.aios_tool_invocations where agent_id=p_agent_id and status='denied'; select count(*) into r from public.aios_approvals where agent_id=p_agent_id and status='rejected'; select coalesce(avg(overall_score),0) into a from public.aios_evaluations where agent_id=p_agent_id; return jsonb_build_object('agent_id',p_agent_id,'stored_trust_score',s,'computed_trust_score',round(greatest(0,least(100,coalesce(a,0)*100*0.5+c*5-f*5-d*3-r*2)),1),'positive',jsonb_build_array(format('%s completed tasks',c),format('evaluation average %s',round(a,3))),'negative',jsonb_build_array(format('%s failed tasks',f),format('%s denied invocations',d),format('%s rejected approvals',r))); end; $$;
create or replace function public.aios_agent_trust_explain(p_agent_id uuid) returns jsonb language sql stable security invoker set search_path='' as $$ select private.aios_agent_trust_explain($1); $$;

create or replace function private.aios_create_agent(p_organization_id uuid,p_name text,p_role text,p_primary_model text,p_risk_level text default 'low',p_allowed_tools jsonb default '[]'::jsonb,p_limits jsonb default '{}'::jsonb,p_department_id uuid default null) returns public.aios_agents language plpgsql security definer set search_path='' as $$ declare v public.aios_agents; k text; begin if not private.aios_is_org_admin(p_organization_id) then raise exception 'only an organization owner/admin can create agents'; end if; if p_risk_level not in('low','medium','high') then raise exception 'invalid risk level'; end if; k=lower(regexp_replace(p_name,'[^a-zA-Z0-9]+','-','g'))||'-'||substr(gen_random_uuid()::text,1,8); insert into public.aios_agents(organization_id,department_id,agent_key,name,role,status,primary_model,trust_score,authority,metadata) values(p_organization_id,p_department_id,k,p_name,p_role,'idle',p_primary_model,0,jsonb_build_object('risk_level',p_risk_level,'allowed_tools',p_allowed_tools,'limits',p_limits),'{}'::jsonb) returning * into v; insert into public.aios_contracts(organization_id,agent_id,version,risk_level,allowed_tools,limits,is_active) values(p_organization_id,v.id,1,p_risk_level,p_allowed_tools,p_limits,true); return v; end; $$;
create or replace function public.aios_create_agent(p_organization_id uuid,p_name text,p_role text,p_primary_model text,p_risk_level text default 'low',p_allowed_tools jsonb default '[]'::jsonb,p_limits jsonb default '{}'::jsonb,p_department_id uuid default null) returns public.aios_agents language sql security invoker set search_path='' as $$ select private.aios_create_agent($1,$2,$3,$4,$5,$6,$7,$8); $$;
create or replace function private.aios_update_agent_authority(p_agent_id uuid,p_risk_level text,p_allowed_tools jsonb,p_limits jsonb) returns public.aios_contracts language plpgsql security definer set search_path='' as $$ declare o uuid; n int; v public.aios_contracts; begin select organization_id into o from public.aios_agents where id=p_agent_id; if not private.aios_is_org_admin(o) then raise exception 'not authorized'; end if; select coalesce(max(version),0)+1 into n from public.aios_contracts where agent_id=p_agent_id; update public.aios_contracts set is_active=false where agent_id=p_agent_id and is_active; insert into public.aios_contracts(organization_id,agent_id,version,risk_level,allowed_tools,limits,is_active) values(o,p_agent_id,n,p_risk_level,p_allowed_tools,p_limits,true) returning * into v; update public.aios_agents set authority=jsonb_build_object('risk_level',p_risk_level,'allowed_tools',p_allowed_tools,'limits',p_limits) where id=p_agent_id; return v; end; $$;
create or replace function public.aios_update_agent_authority(p_agent_id uuid,p_risk_level text,p_allowed_tools jsonb,p_limits jsonb) returns public.aios_contracts language sql security invoker set search_path='' as $$ select private.aios_update_agent_authority($1,$2,$3,$4); $$;
create or replace function private.aios_suspend_agent(p_agent_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare o uuid; begin select organization_id into o from public.aios_agents where id=p_agent_id; if not private.aios_is_org_admin(o) then raise exception 'not authorized'; end if; update public.aios_agents set status='suspended' where id=p_agent_id; end; $$;
create or replace function public.aios_suspend_agent(p_agent_id uuid) returns void language sql security invoker set search_path='' as $$ select private.aios_suspend_agent($1); $$;
create or replace function private.aios_reactivate_agent(p_agent_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare o uuid; begin select organization_id into o from public.aios_agents where id=p_agent_id; if not private.aios_is_org_admin(o) then raise exception 'not authorized'; end if; update public.aios_agents set status='idle' where id=p_agent_id; end; $$;
create or replace function public.aios_reactivate_agent(p_agent_id uuid) returns void language sql security invoker set search_path='' as $$ select private.aios_reactivate_agent($1); $$;

revoke execute on function public.aios_agent_trust_explain(uuid) from anon; revoke execute on function public.aios_can_approve(uuid) from anon; revoke execute on function public.aios_can_manage_agent(uuid) from anon; revoke execute on function public.aios_can_manage_contract(uuid) from anon; revoke execute on function public.aios_create_agent(uuid,text,text,text,text,jsonb,jsonb,uuid) from anon; revoke execute on function public.aios_current_org_role(uuid) from anon; revoke execute on function public.aios_is_org_admin(uuid) from anon; revoke execute on function public.aios_is_org_member(uuid) from anon; revoke execute on function public.aios_reactivate_agent(uuid) from anon; revoke execute on function public.aios_suspend_agent(uuid) from anon; revoke execute on function public.aios_update_agent_authority(uuid,text,jsonb,jsonb) from anon; revoke execute on function public.verify_audit_chain(uuid) from anon;
revoke all on function private.aios_is_org_member(uuid) from public,anon; revoke all on function private.aios_is_org_admin(uuid) from public,anon; revoke all on function private.aios_current_org_role(uuid) from public,anon; revoke all on function private.aios_enforce_agent_authority() from public,anon,authenticated; revoke all on function private.aios_audit_append() from public,anon,authenticated; revoke all on function private.aios_audit_immutable() from public,anon,authenticated; revoke all on function private.verify_audit_chain(uuid) from public,anon; revoke all on function private.aios_agent_trust_explain(uuid) from public,anon; revoke all on function private.aios_record_evaluation(uuid,uuid,numeric,numeric,numeric,numeric,numeric,text) from public,anon,authenticated;

insert into public.aios_tools(tool_key,name,description,version,category,risk_level,input_schema,output_schema,handler,status,is_enabled,requires_approval,external_service,capabilities) values('support.search_tickets','Support Ticket Search','Read-only structured search over the support dataset used by the demo integration.',1,'support','low','{"type":"object","properties":{"query":{"type":"string","maxLength":200},"filters":{"type":"object","additionalProperties":false},"limit":{"type":"integer","minimum":1,"maximum":50}},"required":["limit"],"additionalProperties":false}','{"type":"object","required":["tickets","count","summary"]}','support.search_tickets','active',true,false,'aios_demo_support_tickets','{"read_only":true,"external_side_effect":false}'::jsonb) on conflict(tool_key) do update set input_schema=excluded.input_schema,output_schema=excluded.output_schema,handler=excluded.handler,is_enabled=true,status='active',requires_approval=false,updated_at=now();
update public.aios_contracts set is_active=false where agent_id='177c2599-fc27-4792-b1d6-104b0cf02876' and is_active;
insert into public.aios_contracts(organization_id,agent_id,version,risk_level,allowed_tools,limits,is_active) select organization_id,id,coalesce((select max(c.version)+1 from public.aios_contracts c where c.agent_id=aios_agents.id),1),'low',jsonb_build_array('support.search_tickets'),'{}'::jsonb,true from public.aios_agents where id='177c2599-fc27-4792-b1d6-104b0cf02876';
update public.aios_agents set authority=jsonb_build_object('risk_level','low','allowed_tools',jsonb_build_array('support.search_tickets'),'limits','{}'::jsonb),primary_model=coalesce(primary_model,'Claude') where id='177c2599-fc27-4792-b1d6-104b0cf02876';
commit;
